# Generated by Django 3.2.6 on 2021-12-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_titulo', models.CharField(max_length=200)),
                ('curso_contenido', models.DateTimeField(verbose_name='Fecha de publicación')),
            ],
        ),
    ]
